use_frameworks!

target 'SimpleImageSlider_Example' do
  pod 'SimpleImageSlider', :path => '../'
  pod 'AFNetworking'
  pod 'VGParallaxHeader'
  
  
  target 'SimpleImageSlider_Tests' do
    inherit! :search_paths

    
  end
end
